spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/dbconsultorio?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Fioritech123.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
