spring.application.name=car
server.port=8080
# OAuth2 Client Registration Properties
# Replace 'myoauth2client' with your actual client registration ID (e.g., 'google', 'github', 'okta')
#


server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-exception=true

app.server.base-url=http://localhost:8081
app.mercadopago.notification-url=http://localhost:8081/mercadopago/webhook
