spring.application.name=clientead
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/appServer?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.security.user.name=admin
spring.security.user.password=123456
documentacion.base-path=/home/f4cul3ll4/documentacion
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
