spring.application.name=clientead
server.port=8081
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


cliente.backend.base-url=http://localhost:8080
cliente.backend.auth-path=/seguridad/auth
documentacion.base-path=/home/f4cul3ll4/documentacion
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
